/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.estudiante.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.upemor.controllers.PedidosControlador;
import org.upemor.models.Pedidos;
import org.upemor.models.Usuarios;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.views.forms.VistaDetallePedido;

/**
 *
 * @author Admin
 */
/**
 * Panel de pedidos para estudiantes.
 * Permite ver, buscar, y eliminar pedidos asociados al usuario.
 * Se comunica con otras vistas mediante el sistema de notificaciones global.
 */
public class ApartadoPedidos extends javax.swing.JPanel implements Receptor {

    /** Controlador para operaciones sobre pedidos */
    private PedidosControlador pedidosCTR;
    /** Usuario autenticado */
    private Usuarios usuario;
    /** Referencia al frame padre para mostrar diálogos modales */
    private JFrame framePadre;

    /**
     * Creates new form ApartadoPedidos
     */

    /**
     * Constructor. Inicializa componentes y configura la lista de pedidos.
     */
    public ApartadoPedidos() {
        NotificadorGlobal.getInstancia().registrar(this);
        pedidosCTR = new PedidosControlador();
        initComponents();
        panelListaEntidades.tieneEdicion(false);
        panelListaEntidades.setVistaDetalles();
    }


    /**
     * Asigna el frame padre para mostrar diálogos modales.
     * @param framePadre Ventana principal
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }


    /**
     * Asigna el usuario autenticado y configura la búsqueda y eliminación de pedidos.
     * @param usuario Usuario autenticado
     */
    public void setUsuario(Usuarios usuario) {
        this.usuario = usuario;
        panelListaEntidades.tieneEliminacion(usuario.getRol().equals("estudiante"));
        cargarVista(usuario.getId());
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades.actualizarLista(pedidosCTR.buscarPorIdUsuarioConFolio(usuario.getId(), t));
        });
    }


    /**
     * Carga la lista de pedidos del usuario en el panel principal.
     * @param idUsuario ID del usuario
     */
    public void cargarVista(long idUsuario) {
        panelListaEntidades.actualizarLista(pedidosCTR.buscarPorIdUsuario(idUsuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<Pedidos>();

        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.widgets.Encabezado encabezado;
    private org.upemor.widgets.PanelListaEntidades<Pedidos> panelListaEntidades;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que recibe notificaciones globales para actualizar, mostrar detalles o eliminar pedidos.
     * @param msg Mensaje recibido
     * @param objetos Objetos relacionados con el mensaje
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("actualizacion de Pedido")) {
            // Actualiza la lista de pedidos
            cargarVista(usuario.getId());
        }
        if (msg.equals("detalle Pedidos")) {
            // Muestra el detalle de un pedido en un diálogo modal
            if (framePadre == null) return;
            Pedidos pedido = (Pedidos) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Detalle pedido", true);
            dialogo.add(new VistaDetallePedido(dialogo, pedido, usuario.getRol()));
            dialogo.setSize(555, 820);
            dialogo.setLocationRelativeTo(this);
            dialogo.setVisible(true);
        }
        if (msg.equals("eliminacion Pedidos")) {
            // Elimina un pedido si está cancelado y el usuario lo confirma
            Pedidos pedido = (Pedidos) objetos[0];
            if (!pedido.getEstado().equals("cancelado")) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar un pedido que no está cancelado.");
                return;
            }
            int OK = JOptionPane.showConfirmDialog(this, "Seguri de eliminar el pedido", "Borrar pedido", JOptionPane.YES_NO_OPTION);
            if (OK == JOptionPane.YES_OPTION) {
                try {
                    pedidosCTR.eliminar(pedido.getId());
                    panelListaEntidades.actualizarLista(pedidosCTR.buscarPorIdUsuario(usuario.getId()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        }
    }
}
