/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.estudiante.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.upemor.controllers.SugerenciasControlador;
import org.upemor.models.Sugerencias;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.utils.Validadores;
import org.upemor.views.forms.FormularioSugerencia;

/**
 *
 * @author Admin
 */
/**
 * Panel de sugerencias para estudiantes.
 * Permite ver, buscar, agregar, editar y eliminar sugerencias asociadas al usuario.
 * Se comunica con otras vistas mediante el sistema de notificaciones global.
 */
public class ApartadoSugerencias extends javax.swing.JPanel implements Receptor {

    /** Controlador para operaciones sobre sugerencias */
    private SugerenciasControlador sugerenciasCTR;
    /** Referencia al frame padre para mostrar diálogos modales */
    private JFrame framePadre;
    /** ID del usuario autenticado */
    private long idUsuario;

    /**
     * Creates new form ApartadoSugerencias
     */   

    /**
     * Constructor. Inicializa componentes y registra el panel como receptor de notificaciones.
     */
    public ApartadoSugerencias() {
        NotificadorGlobal.getInstancia().registrar(this);
        initComponents();
        this.idUsuario = 0;
        this.sugerenciasCTR = new SugerenciasControlador();
    }
    

    /**
     * Asigna el frame padre para mostrar diálogos modales.
     * @param framePadre Ventana principal
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }


    /**
     * Asigna el ID del usuario y configura la búsqueda de sugerencias por asunto.
     * @param idUsuario ID del usuario autenticado
     */
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
        encabezado1.setBusquedaAccion(t -> {
            panelListaEntidades1.actualizarLista(sugerenciasCTR.buscarPorAsuntoConIdUsuario(idUsuario, t));
        });
        cargarVista();
    }


    /**
     * Obtiene el ID del usuario autenticado.
     * @return ID del usuario
     */
    public long getIdUsuario() {
        return idUsuario;
    }
    

    /**
     * Carga la lista de sugerencias del usuario en el panel principal.
     */
    public void cargarVista() {
        panelListaEntidades1.actualizarLista(sugerenciasCTR.obtenerTodoPorIdUsuario(idUsuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado1 = new org.upemor.widgets.Encabezado();
        panelListaEntidades1 = new org.upemor.widgets.PanelListaEntidades<Sugerencias>();
        jPanel1 = new javax.swing.JPanel();
        campoAsunto = new javax.swing.JTextField();
        bttnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoComentario = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1022, 720));
        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado1.setMostrarBusqueda(true);
        encabezado1.setTitulo("Sugerencias");

        campoAsunto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bttnAgregar.setBackground(new java.awt.Color(51, 51, 51));
        bttnAgregar.setText("+");
        bttnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Asunto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hacer una sugerencia");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Comentario");

        campoComentario.setColumns(20);
        campoComentario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoComentario.setLineWrap(true);
        campoComentario.setRows(5);
        jScrollPane1.setViewportView(campoComentario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoAsunto)
                        .addGap(18, 18, 18)
                        .addComponent(bttnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(encabezado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Acción al presionar el botón de agregar sugerencia.
     * Valida los campos y registra la sugerencia en la base de datos.
     */
    private void bttnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAgregarActionPerformed
        if (idUsuario == 0) return;
        String asunto = campoAsunto.getText();
        String comentario = campoComentario.getText();
        try {
            Validadores.validarTexto(comentario);
            Validadores.validarTexto(comentario);
            sugerenciasCTR.insertar(idUsuario, asunto, comentario);
            campoAsunto.setText("");
            campoComentario.setText("");
            cargarVista();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Campo invalido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAgregar;
    private javax.swing.JTextField campoAsunto;
    private javax.swing.JTextArea campoComentario;
    private org.upemor.widgets.Encabezado encabezado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.upemor.widgets.PanelListaEntidades<Sugerencias> panelListaEntidades1;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que recibe notificaciones globales para editar o eliminar sugerencias.
     * @param msg Mensaje recibido
     * @param objetos Objetos relacionados con el mensaje
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (framePadre == null) return;
        if (msg.equals("edicion Sugerencias")) {
            // Muestra el formulario de edición de sugerencia en un diálogo modal
            Sugerencias sugerencia = (Sugerencias) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Editar", true);
            dialogo.setSize(600,600);
            dialogo.setLocationRelativeTo(this);
            dialogo.add(new FormularioSugerencia(this, dialogo, sugerencia));
            dialogo.setVisible(true);
        }
        if (msg.equals("eliminacion Sugerencias")) {
            // Confirma y elimina la sugerencia seleccionada
            Sugerencias sugerencia = (Sugerencias) objetos[0];
            int OK = JOptionPane.showConfirmDialog(this, "Seguro?", "Eliminar sugerencia", JOptionPane.YES_NO_OPTION);
            if (OK == 1) return;
            sugerenciasCTR.eliminar(sugerencia.getId());
            cargarVista();
        }
    }
}
