/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.estudiante.screens;

import org.upemor.models.Notificaciones;
import org.upemor.models.Usuarios;
import org.upemor.repositories.NotificacionesRespositorio;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;

/**
 *
 * @author Admin
 */
/**
 * Panel de notificaciones para estudiantes.
 * Permite ver y buscar notificaciones asociadas al usuario.
 * Se comunica con otras vistas mediante el sistema de notificaciones global.
 */
public class ApartadoNotificaciones extends javax.swing.JPanel implements Receptor {
    /** Repositorio para operaciones sobre notificaciones */
    private NotificacionesRespositorio notificacionesRPS;
    /** ID del usuario autenticado */
    private long idUsuario;
    /**
     * Creates new form ApartadoNotificaciones
     */

    /**
     * Constructor. Inicializa componentes y configura la lista de notificaciones.
     */
    public ApartadoNotificaciones() {
        NotificadorGlobal.getInstancia().registrar(this);
        notificacionesRPS = new NotificacionesRespositorio();
        initComponents();
        panelListaEntidades.setModo(panelListaEntidades.MODO_VISTA);
        panelListaEntidades.tieneEdicion(false);
        panelListaEntidades.tieneEliminacion(false);
    }


    /**
     * Asigna el usuario autenticado y configura la búsqueda de notificaciones.
     * @param usuario Usuario autenticado
     */
    public void setUsuario(Usuarios usuario) {
        idUsuario = usuario.getId();
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades.actualizarLista(notificacionesRPS.buscarPorIdUsuarioConMensaje(idUsuario, t));
        });
        cargarNotificaciones();
    }


    /**
     * Carga la lista de notificaciones del usuario en el panel principal.
     */
    private void cargarNotificaciones() {
        if (idUsuario != 0) panelListaEntidades.actualizarLista(notificacionesRPS.buscarPorIdUsuario(idUsuario));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<Notificaciones>();

        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Notificaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.widgets.Encabezado encabezado;
    private org.upemor.widgets.PanelListaEntidades<Notificaciones> panelListaEntidades;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que recibe notificaciones globales para actualizar la lista de notificaciones.
     * @param msg Mensaje recibido
     * @param objetos Objetos relacionados con el mensaje
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("eliminacion Pedidos") || 
            msg.equals("actualizacion de Pedido")) {
            cargarNotificaciones();
        }
    }
}
