/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.estudiante.screens;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JFrame;

import org.upemor.controllers.ProductosControlador;
import org.upemor.models.ItemDetallePedido;
import org.upemor.models.Productos;
import org.upemor.models.Usuarios;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.views.forms.VistaPedidos;
import org.upemor.views.forms.VistaProducto;

/**
 *
 * @author Admin
 */
/**
 * Panel principal del menú de inicio para estudiantes.
 * Permite buscar productos, ver detalles, agregar al carrito y gestionar el pedido.
 * Se comunica con otras vistas mediante el sistema de notificaciones global.
 */
public class MenuInicio extends javax.swing.JPanel implements Receptor {

    /** Controlador para operaciones sobre productos */
    private ProductosControlador productosCTR;
    /** Lista de productos agregados al carrito de compras */
    private List<ItemDetallePedido> listaCarrito = new ArrayList<>();
    /** Referencia al frame padre para mostrar diálogos modales */
    private JFrame framePadre;
    /** Usuario autenticado */
    private Usuarios usuario;

    /**
     * Creates new form MenuInicio
     */

    /**
     * Constructor. Inicializa componentes y configura la búsqueda y la lista de productos.
     */
    public MenuInicio() {
        // Se registra como receptor de notificaciones globales
        NotificadorGlobal.getInstancia().registrar(this);
        productosCTR = new ProductosControlador();
        initComponents();
        // Configura la acción de búsqueda en el encabezado
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades1.actualizarLista(productosCTR.buscarPorNombre(t));
        });
        // Desactiva edición y eliminación en la lista de productos
        panelListaEntidades1.tieneEdicion(false);
        panelListaEntidades1.tieneEliminacion(false);
        panelListaEntidades1.setVistaDetalles();
        // Carga la vista inicial con todos los productos
        cargarVista();
    }


    /**
     * Asigna el usuario autenticado a la vista.
     * @param usuario Usuario autenticado
     */
    public void setUsuario(Usuarios usuario) {
        this.usuario = usuario;
    }


    /**
     * Asigna el frame padre para mostrar diálogos modales.
     * @param framePadre Ventana principal
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }


    /**
     * Carga la lista de todos los productos en el panel principal.
     */
    public void cargarVista() {
        panelListaEntidades1.actualizarLista(productosCTR.obtenerTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        jPanel1 = new javax.swing.JPanel();
        bttnCarrito = new javax.swing.JButton();
        panelListaEntidades1 = new org.upemor.widgets.PanelListaEntidades<Productos>();

        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Menu");

        bttnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping.png"))); // NOI18N
        bttnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Acción al presionar el botón del carrito.
     * Muestra el diálogo con el resumen del pedido actual.
     */
    private void bttnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCarritoActionPerformed
        JDialog dialogo = new JDialog(framePadre, "Carrito del pedido", true);
        VistaPedidos vistaPedidos = new VistaPedidos(dialogo, listaCarrito);
        vistaPedidos.setUsuario(usuario);
        dialogo.setSize(508, 650);
        dialogo.add(vistaPedidos);
        dialogo.setLocationRelativeTo(framePadre);
        dialogo.setVisible(true);
    }//GEN-LAST:event_bttnCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCarrito;
    private org.upemor.widgets.Encabezado encabezado;
    private javax.swing.JPanel jPanel1;
    private org.upemor.widgets.PanelListaEntidades<Productos> panelListaEntidades1;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que recibe notificaciones globales para actualizar el carrito o mostrar detalles de productos.
     * @param msg Mensaje recibido
     * @param objetos Objetos relacionados con el mensaje
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("borrar Pedido")) {
            // Limpia el carrito
            listaCarrito.clear();
            listaCarrito = new ArrayList<>();
        }
        if (msg.equals("cerrar Carrito")) {
            // Actualiza el carrito con la lista recibida
            @SuppressWarnings("unchecked")
            List<ItemDetallePedido> listaCarrito = (List<ItemDetallePedido>) objetos[0];
            this.listaCarrito = listaCarrito;
        }
        if (msg.equals("agregar Carrito")) {
            // Agrega o actualiza un producto en el carrito
            ItemDetallePedido itm = (ItemDetallePedido) objetos[0];
            for (int i = 0; i < listaCarrito.size(); i++) {
                ItemDetallePedido item = listaCarrito.get(i);
                if (item.getProducto().getId() == itm.getProducto().getId()) {
                    if (itm.getCantidad() <= 0) {
                        listaCarrito.remove(i);
                        return;
                    }
                    item.setCantidad(itm.getCantidad());
                    item.setTotal(itm.getTotal());
                    item.setObservacion(itm.getObservacion());
                    return;
                }
            }
            listaCarrito.add(itm);
        }
        if (msg.equals("detalle Productos")) {
            // Muestra el detalle de un producto en un diálogo modal
            Productos producto = (Productos) objetos[0];
            JDialog dialog = new JDialog(framePadre, "Ver producto", true);
            int cantidad = 0;
            String observacion = "";
            if (listaCarrito.size() > 0) {
                for (ItemDetallePedido itm : listaCarrito) {
                    if (itm.getProducto().getId() == producto.getId()) {
                        cantidad = itm.getCantidad();
                        observacion = itm.getObservacion();
                        break;
                    }
                }
            }
            VistaProducto vistaProducto = new VistaProducto(dialog, producto, cantidad, observacion);
            dialog.setSize(850, 800);
            dialog.add(vistaProducto);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }
    }
}
