/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.gui.estudiantes.screens;

import org.upemor.models.entities.Usuarios;

/**
 *
 * @author Admin
 */
public class Cuenta extends javax.swing.JPanel {

    /**
     * Creates new form Cuenta
     */
    public Cuenta() {
        initComponents();
    }
    
    public Cuenta(Usuarios usuario) {
        initComponents();

        textoNombre.setText(textoNombre.getText() + usuario.getNombre());
        textoApellidos.setText(textoApellidos.getText() + usuario.getApellidoPaterno() + " " + usuario.getApellidoMaterno());
        textoMatricula.setText(textoMatricula.getText() + usuario.getMatricula());
        textoCorreo.setText(textoCorreo.getText() + usuario.getCorreo());
        textoTelefono.setText(textoTelefono.getText() + usuario.getTelefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoNombre = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JLabel();
        textoMatricula = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(782, 720));
        setMinimumSize(new java.awt.Dimension(782, 720));
        setPreferredSize(new java.awt.Dimension(782, 720));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cuenta");

        textoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNombre.setText("Nombre: ");

        textoApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoApellidos.setText("Apellidos: ");

        textoMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoMatricula.setText("Matricula: ");

        textoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoCorreo.setText("Correo: ");

        textoTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoTelefono.setText("Telefono: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoNombre)
                    .addComponent(textoApellidos)
                    .addComponent(textoMatricula)
                    .addComponent(textoCorreo)
                    .addComponent(textoTelefono))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoNombre)
                .addGap(18, 18, 18)
                .addComponent(textoApellidos)
                .addGap(18, 18, 18)
                .addComponent(textoMatricula)
                .addGap(18, 18, 18)
                .addComponent(textoCorreo)
                .addGap(18, 18, 18)
                .addComponent(textoTelefono)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoCorreo;
    private javax.swing.JLabel textoMatricula;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoTelefono;
    // End of variables declaration//GEN-END:variables
}
