/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.upemor.views;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.upemor.models.Usuarios;
import org.upemor.theme.Colores;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.views.admin.MenuAdmin;
import org.upemor.views.estudiante.Dashboard;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author Admin
 */

/**
 * Ventana principal del sistema UpeEats.
 * Permite seleccionar el tipo de usuario (Estudiante o Empleado) para iniciar sesión.
 * Según el tipo, muestra el formulario de acceso correspondiente y, tras autenticación,
 * redirige al dashboard adecuado.
 */
public class Main extends javax.swing.JFrame {
    /**
     * Constructor de la ventana principal.
     * Inicializa componentes y asigna el frame padre a los formularios de acceso.
     */
    public Main() {
        // Limpia notificaciones globales previas
        NotificadorGlobal.getInstancia().removerTodos();
        // Inicializa los componentes gráficos
        initComponents();
        // Asigna el frame padre a los formularios de acceso
        accesoEmpleado.setFramePadre(this);
        accesoEstudiante.setFramePadre(this);
    }


    /**
     * Muestra el dashboard correspondiente según el rol del usuario autenticado.
     * Si el usuario es estudiante, abre el dashboard de estudiante; si es empleado/admin, abre el menú de administración.
     * @param usuario Usuario autenticado
     */
    public void mostrarDashboard(Usuarios usuario) {
        if (usuario == null) return;
        // Selecciona el dashboard según el rol
        JFrame dashboard = usuario.getRol().equals("estudiante") ? new Dashboard(usuario) : new MenuAdmin(usuario);
        // Cierra la ventana actual y muestra el dashboard
        this.dispose();
        dashboard.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttnEstudiante = new javax.swing.JButton();
        bttnEmpleado = new javax.swing.JButton();
        layerPanel = new javax.swing.JLayeredPane();
        accesoEstudiante = new org.upemor.views.auth.AccesoEstudiante();
        accesoEmpleado = new org.upemor.views.auth.AccesoEmpleado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceder al sistema");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(380, 1028));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 179));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/LOGO_U4.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UpeEats");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bttnEstudiante.setBackground(new java.awt.Color(239, 55, 67));
        bttnEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        bttnEstudiante.setText("Estudiante");
        bttnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEstudianteActionPerformed(evt);
            }
        });

        bttnEmpleado.setBackground(new java.awt.Color(51, 51, 51));
        bttnEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnEmpleado.setText("Empleado");
        bttnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        layerPanel.setLayout(new java.awt.CardLayout());
        layerPanel.add(accesoEstudiante, "card3");
        layerPanel.add(accesoEmpleado, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 884, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layerPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Cambia el color del botón seleccionado y restablece el de los demás.
     * @param boton Botón que fue seleccionado
     */
    private void seleccionarBoton(JButton boton) {
        bttnEmpleado.setBackground(Colores.CONTRA_FONDO);
        bttnEmpleado.setForeground(Colores.TEXTO_TENUE);
        bttnEstudiante.setBackground(Colores.CONTRA_FONDO);
        bttnEstudiante.setForeground(Colores.TEXTO_TENUE);
        boton.setBackground(Colores.PRIMARIO);
        boton.setForeground(Colores.TEXTO);
    }


    /**
     * Muestra el panel recibido en el área principal de la ventana.
     * @param panel Panel a mostrar (formulario de acceso)
     */
    private void mostrarContenido(JPanel panel) {
        layerPanel.removeAll();
        layerPanel.add(panel);
        layerPanel.revalidate();
        layerPanel.repaint();
    }


    /**
     * Acción al presionar el botón "Estudiante".
     * Selecciona el botón y muestra el formulario de acceso para estudiantes.
     */
    private void bttnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEstudianteActionPerformed
        seleccionarBoton(bttnEstudiante);
        mostrarContenido(accesoEstudiante);
    }//GEN-LAST:event_bttnEstudianteActionPerformed

    /**
     * Acción al presionar el botón "Empleado".
     * Selecciona el botón y muestra el formulario de acceso para empleados.
     */
    private void bttnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEmpleadoActionPerformed
        seleccionarBoton(bttnEmpleado);
        mostrarContenido(accesoEmpleado);
    }//GEN-LAST:event_bttnEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     * Método principal. Inicia la aplicación y muestra la ventana principal.
     * Aplica el tema visual FlatMacDarkLaf.
     */
    public static void main(String args[]) {
        try {
            // Establece el tema oscuro tipo macOS
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // Crea y muestra la ventana principal en el hilo de eventos de Swing
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.views.auth.AccesoEmpleado accesoEmpleado;
    private org.upemor.views.auth.AccesoEstudiante accesoEstudiante;
    private javax.swing.JButton bttnEmpleado;
    private javax.swing.JButton bttnEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane layerPanel;
    // End of variables declaration//GEN-END:variables
}
