/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.admin.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.upemor.controllers.ProductosControlador;
import org.upemor.models.Productos;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.views.forms.FormularioProducto;
import org.upemor.views.forms.VistaProducto;

/**
 * Panel de administración para la gestión de productos en el sistema.
 * @author Admin
 */
public class PantallaProductos extends javax.swing.JPanel implements Receptor{

    /**
     * Controlador encargado de la lógica de negocio para productos.
     */
    private ProductosControlador productosCTR;

    /**
     * Referencia al JFrame padre para mostrar diálogos modales.
     */
    private JFrame framePadre;


    /**
     * Establece el JFrame padre para los diálogos modales.
     * @param framePadre Ventana principal de la aplicación.
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }


    /**
     * Constructor. Inicializa componentes, registra el panel como receptor de notificaciones
     * y configura la lista de productos.
     */
    public PantallaProductos() {
        // Registrar este panel para recibir notificaciones globales
        NotificadorGlobal.getInstancia().registrar(this);
        productosCTR = new ProductosControlador();
        initComponents();
        // Configurar la lista para mostrar detalles de productos
        panelListaEntidades.setVistaDetalles();
        // Cargar todos los productos al iniciar
        cargarVista();

        // Configurar acción de búsqueda en el encabezado
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades.actualizarLista(productosCTR.buscarPorNombre(t));
        });
    }


    /**
     * Carga y muestra todos los productos en el panel de lista.
     */
    public void cargarVista() {
        panelListaEntidades.actualizarLista(productosCTR.obtenerTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<Productos>();
        jScrollPane1 = new javax.swing.JScrollPane();
        formularioProducto1 = new org.upemor.views.forms.FormularioProducto();

        setMaximumSize(new java.awt.Dimension(1022, 720));
        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Lista de productos");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(formularioProducto1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.widgets.Encabezado encabezado;
    private org.upemor.views.forms.FormularioProducto formularioProducto1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.upemor.widgets.PanelListaEntidades<Productos> panelListaEntidades;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que responde a notificaciones globales.
     * <ul>
     *   <li>"edicion Productos": Abre un diálogo para editar el producto seleccionado.</li>
     *   <li>"detalle Productos": Abre un diálogo para ver el detalle del producto seleccionado.</li>
     *   <li>"agregar Productos": Recarga la lista de productos.</li>
     *   <li>"eliminacion Productos": Solicita confirmación y elimina el producto seleccionado.</li>
     *   <li>"eliminacion Categorias"/"actualizacion Categorias": Recarga la lista de productos.</li>
     * </ul>
     * @param msg Mensaje de notificación recibido.
     * @param objetos Parámetros adicionales enviados con la notificación.
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("edicion Productos")) {
            Productos producto = (Productos) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Editar producto", true);

            dialogo.setSize(650,750);
            dialogo.setLocationRelativeTo(this);
            dialogo.add(new FormularioProducto(dialogo, producto));
            dialogo.setVisible(true);
            
        }
        if (msg.equals("detalle Productos")) {
            Productos producto = (Productos) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Detalle producto", true);

            dialogo.setSize(850,750);
            dialogo.setLocationRelativeTo(this);
            dialogo.add(new VistaProducto(dialogo, producto));
            dialogo.setVisible(true);
        }

        if (msg.equals("agregar Productos")) {
            cargarVista();
        }

        if (msg.equals("eliminacion Productos")) {
            Productos producto = (Productos) objetos[0];
            
            int OK = JOptionPane.showConfirmDialog(this, "Seguro?", "Eliminar producto", JOptionPane.YES_NO_OPTION);
            if (OK == 1) return;

            productosCTR.eliminar(producto.getId());
            cargarVista();
        }

        if (msg.equals("eliminacion Categorias") || msg.equals("actualizacion Categorias")) {
            cargarVista();
        }
    }
}
