/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.admin.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;

import org.upemor.controllers.PedidosControlador;
import org.upemor.models.Pedidos;
import org.upemor.models.Usuarios;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.views.forms.VistaDetallePedido;

/**
 * Panel de administración para la gestión de pedidos en el sistema UpeEats.
 *
 * @author Admin
 */
public class PantallaPedidos extends javax.swing.JPanel implements Receptor {

    /**
     * Controlador encargado de la lógica de negocio para pedidos.
     */
    private PedidosControlador pedidosCTR;

    /**
     * Referencia al JFrame padre para mostrar diálogos modales.
     */
    private JFrame framePadre;

    /**
     * Usuario actual (usado para mostrar detalles según el rol).
     */
    private Usuarios usuario;


    /**
     * Constructor. Inicializa componentes, registra el panel como receptor de notificaciones
     * y configura la lista de pedidos en modo solo lectura.
     */
    public PantallaPedidos() {
        // Registrar este panel para recibir notificaciones globales
        NotificadorGlobal.getInstancia().registrar(this);
        pedidosCTR = new PedidosControlador();
        initComponents();
        // Configurar acción de búsqueda en el encabezado
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades1.actualizarLista(pedidosCTR.buscarPorFolio(t));
        });
        // Configurar la lista para solo mostrar detalles, sin edición ni eliminación
        panelListaEntidades1.tieneEdicion(false);
        panelListaEntidades1.tieneEliminacion(false);
        panelListaEntidades1.setVistaDetalles();
        // Cargar todos los pedidos al iniciar
        panelListaEntidades1.actualizarLista(pedidosCTR.obtenerTodos());
    }


    /**
     * Establece el JFrame padre y el usuario actual para los diálogos modales.
     * @param framePadre Ventana principal de la aplicación.
     * @param usuario Usuario actual (para mostrar detalles según el rol).
     */
    public void setFramePadreYUsuario(JFrame framePadre, Usuarios usuario) {
        this.framePadre = framePadre;
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades1 = new org.upemor.widgets.PanelListaEntidades<Pedidos>();

        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Lista de pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.widgets.Encabezado encabezado;
    private org.upemor.widgets.PanelListaEntidades<Pedidos> panelListaEntidades1;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que responde a notificaciones globales.
     * <ul>
     *   <li>"actualizacion de Pedido": Recarga la lista de pedidos.</li>
     *   <li>"detalle Pedidos": Muestra un diálogo modal con el detalle del pedido seleccionado.</li>
     * </ul>
     * @param msg Mensaje de notificación recibido.
     * @param objetos Parámetros adicionales enviados con la notificación.
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("actualizacion de Pedido")) {
            panelListaEntidades1.actualizarLista(pedidosCTR.obtenerTodos());
        }

        if (msg.equals("detalle Pedidos")) {
            if (framePadre == null) return;

            Pedidos pedido = (Pedidos) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Detalle pedido", true);

            dialogo.add(new VistaDetallePedido(dialogo, pedido, usuario.getRol()));
            dialogo.setSize(555, 820);
            dialogo.setLocationRelativeTo(this);
            dialogo.setVisible(true);
        }
    }
}
