/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.admin.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.upemor.controllers.UsuariosControlador;
import org.upemor.models.Usuarios;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.views.forms.VistaEmpleados;

/**
 *
 * @author Admin
 */
/**
 * Panel de administración de usuarios.
 * Permite ver, buscar, editar y eliminar usuarios del sistema.
 * Se comunica con otras vistas mediante el sistema de notificaciones global.
 */
public class PantallaUsuarios extends javax.swing.JPanel implements Receptor {

    /** Controlador para operaciones sobre usuarios */
    private UsuariosControlador usuariosCTR;
    /** Referencia al frame padre para mostrar diálogos modales */
    private JFrame framePadre;


    /**
     * Asigna el frame padre para mostrar diálogos modales.
     * @param framePadre Ventana principal
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }

    /**
     * Creates new form PantallaUsuarios
     */

    /**
     * Constructor. Inicializa componentes y configura la lista de usuarios.
     */
    public PantallaUsuarios() {
        NotificadorGlobal.getInstancia().registrar(this);
        usuariosCTR = new UsuariosControlador();
        initComponents();
        panelListaEntidades.setVistaDetalles();
        panelListaEntidades.tieneEdicion(false);
        cargarVista();
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades.actualizarLista(usuariosCTR.buscarPorNombre(t));
        });
    }


    /**
     * Carga la lista de todos los usuarios en el panel principal.
     */
    public void cargarVista() {
        panelListaEntidades.actualizarLista(usuariosCTR.obtenerTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<Usuarios>();

        setMaximumSize(new java.awt.Dimension(1022, 720));
        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setBusquedaAccion(null);
        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Lista de usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.widgets.Encabezado encabezado;
    private org.upemor.widgets.PanelListaEntidades<Usuarios> panelListaEntidades;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que recibe notificaciones globales para mostrar detalles, actualizar o eliminar usuarios.
     * @param msg Mensaje recibido
     * @param objetos Objetos relacionados con el mensaje
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("detalle Usuarios")) {
            // Muestra el formulario de edición de usuario en un diálogo modal
            Usuarios usuario = (Usuarios) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Editar", true);
            dialogo.setSize(600,600);
            dialogo.setLocationRelativeTo(this);
            dialogo.add(new VistaEmpleados(dialogo, usuario));
            dialogo.setVisible(true);
        }
        if (msg.equals("actualizacion lista Usuarios")) {
            // Actualiza la lista de usuarios
            cargarVista();
        }
        if (msg.equals("eliminacion Usuarios")) {
            // Confirma y elimina el usuario seleccionado
            Usuarios usuario = (Usuarios) objetos[0];
            int OK = JOptionPane.showConfirmDialog(this, "Seguro?", "Eliminar usuario", JOptionPane.YES_NO_OPTION);
            if (OK == 1) return;
            usuariosCTR.eliminar(usuario.getId());
            cargarVista();
        }
    }
}
