/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.admin.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

import org.upemor.controllers.CategoriasControlador;
import org.upemor.models.Categorias;
import org.upemor.utils.FiltroEntradas;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.utils.Validadores;
import org.upemor.views.forms.FormularioCategoria;

/**
 * Panel de administración para la gestión de categorías en el sistema.
 *
 * @author Admin
 */
public class PantallaCategorias extends javax.swing.JPanel implements Receptor {

    /**
     * Controlador encargado de la lógica de negocio para categorías.
     */
    private CategoriasControlador categoriasCTR;

    /**
     * Referencia al JFrame padre para mostrar diálogos modales.
     */
    private JFrame framePadre;


    /**
     * Establece el JFrame padre para los diálogos modales y aplica filtros de entrada.
     * @param framePadre Ventana principal de la aplicación.
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
        aplicarFiltros();
    }


    /**
     * Aplica filtros de entrada al campo de nombre para limitar la longitud y evitar SQL injection.
     */
    private void aplicarFiltros() {
        AbstractDocument docCampoNombre = (AbstractDocument) campoNombre.getDocument();
        docCampoNombre.setDocumentFilter(new FiltroEntradas(50, FiltroEntradas.NO_SQL));
    }


    /**
     * Constructor. Inicializa componentes, registra el panel como receptor de notificaciones
     * y configura la lista de categorías.
     */
    public PantallaCategorias() {
        // Registrar este panel para recibir notificaciones globales
        NotificadorGlobal.getInstancia().registrar(this);
        categoriasCTR = new CategoriasControlador();
        initComponents();
        // Cargar todas las categorías al iniciar
        cargarVista();

        // Configurar acción de búsqueda en el encabezado
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades.actualizarLista(categoriasCTR.buscarPorNombre(t));
        });
    }


    /**
     * Carga y muestra todas las categorías en el panel de lista.
     */
    public void cargarVista() {
        panelListaEntidades.actualizarLista(categoriasCTR.obtenerTodas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<Categorias>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        bttnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1022, 720));
        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Lista de categorias");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar categoria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bttnAgregar.setText("+");
        bttnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Descripcion");

        campoDescripcion.setColumns(20);
        campoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDescripcion.setLineWrap(true);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Acción del botón para agregar una nueva categoría.
     * Valida los campos, inserta la categoría y actualiza la vista.
     * Muestra un mensaje de error si la validación falla.
     */
    private void bttnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAgregarActionPerformed
        String nombre = campoNombre.getText();
        String descripcion = campoDescripcion.getText();

        try {
            Validadores.validarNombre(nombre);
            Validadores.validarTexto(descripcion);

            categoriasCTR.insertar(nombre, descripcion);

            campoNombre.setText("");
            campoDescripcion.setText("");

            cargarVista();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Campo invalido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAgregar;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private org.upemor.widgets.Encabezado encabezado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.upemor.widgets.PanelListaEntidades<Categorias> panelListaEntidades;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que responde a notificaciones globales.
     * <ul>
     *   <li>"actualizacion Categorias": Recarga la lista de categorías.</li>
     *   <li>"edicion Categorias": Abre un diálogo para editar la categoría seleccionada.</li>
     *   <li>"eliminacion Categorias": Solicita confirmación y elimina la categoría seleccionada.</li>
     * </ul>
     * @param msg Mensaje de notificación recibido.
     * @param objetos Parámetros adicionales enviados con la notificación.
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("actualizacion Categorias")) {
            cargarVista();
        }
        if (msg.equals("edicion Categorias")) {
            Categorias categoria = (Categorias) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Editar", true);
            // Se establece el tamaño del diálogo
            dialogo.setSize(600,600);

            // Se centra el diálogo respecto a la ventana principal
            dialogo.setLocationRelativeTo(this);
            
            dialogo.add(new FormularioCategoria(dialogo, categoria));
            dialogo.setVisible(true);
            
        }
        if (msg.equals("eliminacion Categorias")) {
            Categorias categoria = (Categorias) objetos[0];
            
            int OK = JOptionPane.showConfirmDialog(this, "Seguro?", "Eliminar categoria", JOptionPane.YES_NO_OPTION);
            if (OK == 1) return;

            categoriasCTR.eliminar(categoria.getId());
            cargarVista();
        }
    }
}
