/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.admin.screens;

import javax.swing.JDialog;
import javax.swing.JFrame;

import org.upemor.controllers.SugerenciasControlador;
import org.upemor.models.Sugerencias;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.views.forms.VistaSugerencia;

/**
 * @author Admin
 */
public class PantallaSugerencias extends javax.swing.JPanel implements Receptor{

    /**
     * Controlador encargado de la lógica de negocio para sugerencias.
     */
    private SugerenciasControlador sugerenciasCTR;

    /**
     * Referencia al JFrame padre para mostrar diálogos modales.
     */
    private JFrame framePadre;


    /**
     * Establece el JFrame padre para los diálogos modales.
     * @param framePadre Ventana principal de la aplicación.
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }


    /**
     * Constructor. Inicializa componentes, registra el panel como receptor de notificaciones
     * y configura la lista de sugerencias en modo solo lectura.
     */
    public PantallaSugerencias() {
        // Registrar este panel para recibir notificaciones globales
        NotificadorGlobal.getInstancia().registrar(this);
        sugerenciasCTR = new SugerenciasControlador();
        initComponents();
        
        // Configurar la lista para solo mostrar detalles, sin edición ni eliminación
        panelListaEntidades.setVistaDetalles();
        panelListaEntidades.tieneEdicion(false);
        panelListaEntidades.tieneEliminacion(false);
        
        // Cargar todas las sugerencias al iniciar
        cargarVista();
        
        // Configurar acción de búsqueda en el encabezado
        encabezado.setBusquedaAccion(t -> {
            panelListaEntidades.actualizarLista(sugerenciasCTR.buscarPorAsunto(t));
        });
    }


    /**
     * Carga y muestra todas las sugerencias en el panel de lista.
     */
    public void cargarVista() {
        panelListaEntidades.actualizarLista(sugerenciasCTR.obtenerTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new org.upemor.widgets.Encabezado();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<Sugerencias>();

        setMaximumSize(new java.awt.Dimension(1022, 720));
        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado.setMostrarBusqueda(true);
        encabezado.setTitulo("Lista de sugerencias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.widgets.Encabezado encabezado;
    private org.upemor.widgets.PanelListaEntidades<Sugerencias> panelListaEntidades;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que responde a notificaciones globales.
     * <ul>
     *   <li>"actualizar lista Sugerencias": Recarga la lista de sugerencias.</li>
     *   <li>"detalle Sugerencias": Muestra un diálogo modal con el detalle de la sugerencia seleccionada.</li>
     * </ul>
     * @param msg Mensaje de notificación recibido.
     * @param objetos Parámetros adicionales enviados con la notificación.
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("actualizar lista Sugerencias")) {
            cargarVista();
        }

        if (msg.equals("detalle Sugerencias")) {
            Sugerencias sugerencia = (Sugerencias) objetos[0];
            JDialog dialogo = new JDialog(framePadre, "Detalle sugerencia", true);

            // Se establece el tamaño del diálogo
            dialogo.setSize(600,600);

            // Se centra el diálogo respecto a la ventana principal
            dialogo.setLocationRelativeTo(this);

            // Se agrega el panel de detalle de sugerencia al diálogo
            dialogo.add(new VistaSugerencia(dialogo, sugerencia));
            dialogo.setVisible(true);
        }
    }
}
