/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.auth;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.upemor.controllers.UsuariosControlador;
import org.upemor.models.Usuarios;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;
import org.upemor.utils.Validadores;
import org.upemor.views.Main;

/**
 *
 * @author Admin
 */
/**
 * Panel de información y edición de cuenta de usuario.
 * Permite ver, editar y actualizar los datos personales del usuario, así como cerrar sesión.
 * Se comunica con otras vistas mediante el sistema de notificaciones global.
 */
public class VistaCuenta extends javax.swing.JPanel implements Receptor{

    /** Usuario autenticado */
    private Usuarios usuario;
    /** Controlador para operaciones sobre usuarios */
    private UsuariosControlador usuariosCTR;
    /** Referencia al frame padre para mostrar diálogos modales */
    private JFrame framePadre;

    /**
     * Asigna el frame padre para mostrar diálogos modales.
     * @param framePadre Ventana principal
     */
    public void setFramePadre(JFrame framePadre) {
        this.framePadre = framePadre;
    }
    /**
     * Creates new form VistaCuenta
     */

    /**
     * Constructor. Inicializa componentes y oculta el botón cancelar por defecto.
     */
    public VistaCuenta() {
        NotificadorGlobal.getInstancia().registrar(this);
        initComponents();
        bttnCancelar.setVisible(false);
    }


    /**
     * Asigna el usuario autenticado y actualiza la información mostrada.
     * @param usuario Usuario autenticado
     */
    public void setUsuario(Usuarios usuario) {
        this.usuario = usuario;
        boolean isEstudiante = usuario.getRol().equals("estudiante");
        textoRolMat.setText(isEstudiante? "Matricula" : "Rol");
        campoRolMat.setText(isEstudiante? usuario.getMatricula(): usuario.getRol());
        cargarInfo();
    }


    /**
     * Carga la información del usuario en los campos de la vista.
     */
    private void cargarInfo() {
        campoNombre.setText(usuario.getNombre());
        campoApellidoPaterno.setText(usuario.getApellidoPaterno());
        campoApellidoMaterno.setText(usuario.getApellidoMaterno());
        campoCorreo.setText(usuario.getCorreo());
        campoTelefono.setText(usuario.getTelefono());
        campoContra.setText(usuario.getContrasenia());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado1 = new org.upemor.widgets.Encabezado();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidoPaterno = new javax.swing.JTextField();
        campoApellidoMaterno = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        bttnVerContra = new javax.swing.JButton();
        campoContra = new javax.swing.JPasswordField();
        textoRolMat = new javax.swing.JLabel();
        campoRolMat = new javax.swing.JLabel();
        bttnEdicion = new javax.swing.JButton();
        bttnCancelar = new javax.swing.JButton();
        bttnCerrarSesion = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1022, 720));
        setMinimumSize(new java.awt.Dimension(1022, 720));
        setPreferredSize(new java.awt.Dimension(1022, 720));

        encabezado1.setTitulo("Informacion de la cuneta");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Apellidos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Contacto");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Contraseña");

        campoNombre.setEditable(false);
        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoApellidoPaterno.setEditable(false);
        campoApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoApellidoMaterno.setEditable(false);
        campoApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoCorreo.setEditable(false);
        campoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        campoTelefono.setEditable(false);
        campoTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bttnVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye-slash.png"))); // NOI18N
        bttnVerContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVerContraActionPerformed(evt);
            }
        });

        campoContra.setEditable(false);
        campoContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoContra.setText("jPasswordField1");

        textoRolMat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoRolMat.setText("Matricula");

        campoRolMat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoRolMat.setText("[Matricula]");

        bttnEdicion.setBackground(new java.awt.Color(33, 150, 243));
        bttnEdicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen-to-square.png"))); // NOI18N
        bttnEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEdicionActionPerformed(evt);
            }
        });

        bttnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bttnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bttnCancelar.setText("Cancelar");
        bttnCancelar.setToolTipText("");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });

        bttnCerrarSesion.setBackground(new java.awt.Color(239, 55, 67));
        bttnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        bttnCerrarSesion.setText("Cerrar sesion");
        bttnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bttnEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnCerrarSesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoRolMat, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoRolMat, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(campoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(campoContra)
                                            .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoContra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bttnVerContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(bttnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoRolMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRolMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(240, 240, 240))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encabezado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(encabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean isModoEdicion = false;


    /**
     * Cambia el modo de edición de los campos de la vista.
     * Si está en modo edición, los campos son editables y se muestra el botón cancelar.
     */
    private void cambioModoEdicion() {
        bttnCancelar.setVisible(isModoEdicion);
        campoNombre.setEditable(isModoEdicion);
        campoApellidoPaterno.setEditable(isModoEdicion);
        campoApellidoMaterno.setEditable(isModoEdicion);
        campoTelefono.setEditable(isModoEdicion);
    }

    /**
     * Acción al presionar el botón de edición.
     * Permite alternar entre modo edición y modo vista, y guardar los cambios si corresponde.
     */
    private void bttnEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEdicionActionPerformed
        if (usuario == null) return;
        if (isModoEdicion) {
            String nombre = campoNombre.getText();
            String apellidoPaterno = campoApellidoPaterno.getText();
            String apellidoMaterno = campoApellidoMaterno.getText();
            String telefono = campoTelefono.getText();
            try {
                Validadores.validarNombre(nombre);
                Validadores.validarApellido(apellidoPaterno);
                Validadores.validarApellido(apellidoMaterno);
                Validadores.validarTelefono(telefono);
                int OK = JOptionPane.showConfirmDialog(this, "Seguro?", "Editar informacion", JOptionPane.YES_NO_OPTION);
                if (OK != 0) return;
                usuariosCTR.editarUsuario(usuario.getId(), nombre, apellidoPaterno, apellidoMaterno, telefono);
                usuario = usuariosCTR.buscarPorId(usuario.getId());
                isModoEdicion = false;
                cambioModoEdicion();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Campo invalido", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (!isModoEdicion) {
            isModoEdicion = true;
            cambioModoEdicion();
        }
    }//GEN-LAST:event_bttnEdicionActionPerformed

    private boolean isVistaContra = false;


    /**
     * Acción al presionar el botón para mostrar/ocultar la contraseña.
     */
    private void bttnVerContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVerContraActionPerformed
        if (usuario == null) return;
        isVistaContra = !isVistaContra;
        if (isVistaContra) {
            bttnVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png")));
            campoContra.setEchoChar((char) 0);
        } else {
            bttnVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye-slash.png")));
            campoContra.setEchoChar('*');
        }
    }//GEN-LAST:event_bttnVerContraActionPerformed


    /**
     * Acción al presionar el botón cancelar.
     * Cancela la edición y restaura la información original.
     */
    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        isModoEdicion = false;
        cargarInfo();
        cambioModoEdicion();
    }//GEN-LAST:event_bttnCancelarActionPerformed


    /**
     * Acción al presionar el botón cerrar sesión.
     * Cierra la sesión actual y regresa a la pantalla principal.
     */
    private void bttnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarSesionActionPerformed
        if (framePadre != null) {
            NotificadorGlobal.getInstancia().removerTodos();
            Main main = new Main();
            framePadre.dispose();
            main.setVisible(true);
        }
    }//GEN-LAST:event_bttnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JButton bttnCerrarSesion;
    private javax.swing.JButton bttnEdicion;
    private javax.swing.JButton bttnVerContra;
    private javax.swing.JTextField campoApellidoMaterno;
    private javax.swing.JTextField campoApellidoPaterno;
    private javax.swing.JPasswordField campoContra;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel campoRolMat;
    private javax.swing.JTextField campoTelefono;
    private org.upemor.widgets.Encabezado encabezado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoRolMat;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que recibe notificaciones globales para actualizar la información del usuario.
     * @param msg Mensaje recibido
     * @param objetos Objetos relacionados con el mensaje
     */
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("actualizacion Usuarios")) {
            Usuarios usuario = (Usuarios) objetos[0];
            setUsuario(usuario);
        }
    }
}
