/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.upemor.views.estudiante;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.upemor.models.Usuarios;
import org.upemor.theme.Colores;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author Admin
 */

/**
 * Ventana principal del estudiante (Dashboard).
 * Permite navegar entre las diferentes secciones: inicio, pedidos, notificaciones, sugerencias y cuenta.
 * Cada sección se muestra en el panel principal según el botón seleccionado.
 */
public class Dashboard extends javax.swing.JFrame {


    /**
     * Constructor principal del dashboard de estudiante.
     * Inicializa los componentes y asigna el usuario a cada sección.
     * @param usuario Usuario autenticado
     */
    public Dashboard(Usuarios usuario) {
        initComponents();
        // Asigna el usuario y el frame padre a cada sección
        apartadoSugerencias.setIdUsuario(usuario.getId());
        apartadoSugerencias.setFramePadre(this);
        vistaCuenta.setUsuario(usuario);
        vistaCuenta.setFramePadre(this);
        menuInicio1.setUsuario(usuario);
        menuInicio1.setFramePadre(this);
        apartadoPedidos.setUsuario(usuario);
        apartadoPedidos.setFramePadre(this);
        apartadoNotificaciones1.setUsuario(usuario);
        // Muestra la pantalla de inicio por defecto
        mostrarContenido(menuInicio1);
    }


    /**
     * Constructor alternativo (sin usuario). Solo para pruebas o vista previa.
     */
    public Dashboard() {
        initComponents();
        mostrarContenido(menuInicio1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttnInicio = new javax.swing.JButton();
        bttnPedidos = new javax.swing.JButton();
        bttnNotificaciones = new javax.swing.JButton();
        bttnSugerencias = new javax.swing.JButton();
        bttnCuenta = new javax.swing.JButton();
        layerPanel = new javax.swing.JLayeredPane();
        apartadoSugerencias = new org.upemor.views.estudiante.screens.ApartadoSugerencias();
        vistaCuenta = new org.upemor.views.auth.VistaCuenta();
        menuInicio1 = new org.upemor.views.estudiante.screens.MenuInicio();
        apartadoPedidos = new org.upemor.views.estudiante.screens.ApartadoPedidos();
        apartadoNotificaciones1 = new org.upemor.views.estudiante.screens.ApartadoNotificaciones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UpeEats");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/LOGO_U4.png"))); // NOI18N

        bttnInicio.setBackground(new java.awt.Color(239, 55, 67));
        bttnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnInicio.setForeground(new java.awt.Color(255, 255, 255));
        bttnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house-solid.png"))); // NOI18N
        bttnInicio.setText("Inicio");
        bttnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnInicioActionPerformed(evt);
            }
        });

        bttnPedidos.setBackground(new java.awt.Color(51, 51, 51));
        bttnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bars-solid.png"))); // NOI18N
        bttnPedidos.setText("Pedidos");
        bttnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPedidosActionPerformed(evt);
            }
        });

        bttnNotificaciones.setBackground(new java.awt.Color(51, 51, 51));
        bttnNotificaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bell-solid.png"))); // NOI18N
        bttnNotificaciones.setText("Notificaciones");
        bttnNotificaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNotificacionesActionPerformed(evt);
            }
        });

        bttnSugerencias.setBackground(new java.awt.Color(51, 51, 51));
        bttnSugerencias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnSugerencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comment-solid.png"))); // NOI18N
        bttnSugerencias.setText("Sugerencias");
        bttnSugerencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnSugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSugerenciasActionPerformed(evt);
            }
        });

        bttnCuenta.setBackground(new java.awt.Color(51, 51, 51));
        bttnCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-solid.png"))); // NOI18N
        bttnCuenta.setText("Cuenta");
        bttnCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(bttnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        layerPanel.setLayout(new java.awt.CardLayout());
        layerPanel.add(apartadoSugerencias, "card2");
        layerPanel.add(vistaCuenta, "card3");
        layerPanel.add(menuInicio1, "card4");
        layerPanel.add(apartadoPedidos, "card5");
        layerPanel.add(apartadoNotificaciones1, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layerPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layerPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    /**
     * Cambia el color del botón seleccionado y restablece el de los demás.
     * @param boton Botón que fue seleccionado
     */
    private void seleccionarBoton(JButton boton) {
        bttnInicio.setBackground(Colores.CONTRA_FONDO);
        bttnCuenta.setBackground(Colores.CONTRA_FONDO);
        bttnNotificaciones.setBackground(Colores.CONTRA_FONDO);
        bttnPedidos.setBackground(Colores.CONTRA_FONDO);
        bttnSugerencias.setBackground(Colores.CONTRA_FONDO);
        boton.setBackground(Colores.PRIMARIO);
    }


    /**
     * Muestra el panel recibido en el área principal de la ventana.
     * @param panel Panel a mostrar (sección seleccionada)
     */
    private void mostrarContenido(JPanel panel) {
        layerPanel.removeAll();
        layerPanel.add(panel);
        layerPanel.revalidate();
        layerPanel.repaint();
    }


    /**
     * Acción al presionar el botón "Inicio".
     * Selecciona el botón y muestra la pantalla de inicio.
     */
    private void bttnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnInicioActionPerformed
        seleccionarBoton(bttnInicio);
        mostrarContenido(menuInicio1);
    }//GEN-LAST:event_bttnInicioActionPerformed


    /**
     * Acción al presionar el botón "Pedidos".
     * Selecciona el botón y muestra la sección de pedidos.
     */
    private void bttnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPedidosActionPerformed
        seleccionarBoton(bttnPedidos);
        mostrarContenido(apartadoPedidos);
    }//GEN-LAST:event_bttnPedidosActionPerformed


    /**
     * Acción al presionar el botón "Notificaciones".
     * Selecciona el botón y muestra la sección de notificaciones.
     */
    private void bttnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNotificacionesActionPerformed
        seleccionarBoton(bttnNotificaciones);
        mostrarContenido(apartadoNotificaciones1);
    }//GEN-LAST:event_bttnNotificacionesActionPerformed


    /**
     * Acción al presionar el botón "Sugerencias".
     * Selecciona el botón y muestra la sección de sugerencias.
     */
    private void bttnSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSugerenciasActionPerformed
        seleccionarBoton(bttnSugerencias);
        mostrarContenido(apartadoSugerencias);
    }//GEN-LAST:event_bttnSugerenciasActionPerformed


    /**
     * Acción al presionar el botón "Cuenta".
     * Selecciona el botón y muestra la sección de cuenta del usuario.
     */
    private void bttnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCuentaActionPerformed
        seleccionarBoton(bttnCuenta);
        mostrarContenido(vistaCuenta);
    }//GEN-LAST:event_bttnCuentaActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     * Método principal. Inicia la aplicación y muestra el dashboard de estudiante.
     * Aplica el tema visual FlatMacDarkLaf.
     */
    public static void main(String args[]) {
        try {
            // Establece el tema oscuro tipo macOS
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // Crea y muestra la ventana principal en el hilo de eventos de Swing
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.upemor.views.estudiante.screens.ApartadoNotificaciones apartadoNotificaciones1;
    private org.upemor.views.estudiante.screens.ApartadoPedidos apartadoPedidos;
    private org.upemor.views.estudiante.screens.ApartadoSugerencias apartadoSugerencias;
    private javax.swing.JButton bttnCuenta;
    private javax.swing.JButton bttnInicio;
    private javax.swing.JButton bttnNotificaciones;
    private javax.swing.JButton bttnPedidos;
    private javax.swing.JButton bttnSugerencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane layerPanel;
    private org.upemor.views.estudiante.screens.MenuInicio menuInicio1;
    private org.upemor.views.auth.VistaCuenta vistaCuenta;
    // End of variables declaration//GEN-END:variables
}
