/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.upemor.views.admin;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.upemor.models.Usuarios;
import org.upemor.theme.Colores;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author Admin
 */
/**
 * Ventana principal del panel de administración.
 * Permite navegar entre las diferentes secciones de gestión: usuarios, sugerencias, productos, categorías, pedidos y cuenta.
 * Cada sección se muestra en el panel principal según el botón seleccionado.
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */

    /**
     * Constructor principal del menú de administración.
     * Inicializa componentes y configura la visibilidad de los botones según el rol.
     * @param usuario Usuario autenticado
     */
    public MenuAdmin(Usuarios usuario) {
        initComponents();
        vistaCuenta.setUsuario(usuario);
        // El botón de usuarios solo es visible para administradores
        bttnUsuarios.setVisible(usuario.getRol().equals("administrador"));
        pantallaPedidos.setFramePadreYUsuario(this, usuario);
        vistaCuenta.setFramePadre(this);
    }


    /**
     * Constructor alternativo (sin usuario). Solo para pruebas o vista previa.
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttnInicio = new javax.swing.JButton();
        bttnCuenta = new javax.swing.JButton();
        bttnUsuarios = new javax.swing.JButton();
        bttnSugerencias = new javax.swing.JButton();
        bttnCategorias = new javax.swing.JButton();
        bttnProductos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttnPedidos = new javax.swing.JButton();
        layerPanel = new javax.swing.JLayeredPane();
        vistaCuenta = new org.upemor.views.auth.VistaCuenta();
        pantallaUsuarios = new org.upemor.views.admin.screens.PantallaUsuarios();
        pantallaSugerencias = new org.upemor.views.admin.screens.PantallaSugerencias();
        pantallaProductos = new org.upemor.views.admin.screens.PantallaProductos();
        pantallaCategorias = new org.upemor.views.admin.screens.PantallaCategorias();
        pantallaPedidos = new org.upemor.views.admin.screens.PantallaPedidos();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        bttnInicio.setBackground(new java.awt.Color(51, 51, 51));
        bttnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house-solid.png"))); // NOI18N
        bttnInicio.setText("Inicio");
        bttnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnInicioActionPerformed(evt);
            }
        });

        bttnCuenta.setBackground(new java.awt.Color(51, 51, 51));
        bttnCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-solid.png"))); // NOI18N
        bttnCuenta.setText("Cuenta");
        bttnCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCuentaActionPerformed(evt);
            }
        });

        bttnUsuarios.setBackground(new java.awt.Color(51, 51, 51));
        bttnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users-solid-full.png"))); // NOI18N
        bttnUsuarios.setText("Usuarios");
        bttnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUsuariosActionPerformed(evt);
            }
        });

        bttnSugerencias.setBackground(new java.awt.Color(51, 51, 51));
        bttnSugerencias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnSugerencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comments.png"))); // NOI18N
        bttnSugerencias.setText("Sugerencias");
        bttnSugerencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnSugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSugerenciasActionPerformed(evt);
            }
        });

        bttnCategorias.setBackground(new java.awt.Color(51, 51, 51));
        bttnCategorias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tags.png"))); // NOI18N
        bttnCategorias.setText("Categorias");
        bttnCategorias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCategoriasActionPerformed(evt);
            }
        });

        bttnProductos.setBackground(new java.awt.Color(51, 51, 51));
        bttnProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image.png"))); // NOI18N
        bttnProductos.setText("Productos");
        bttnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnProductosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Control");

        bttnPedidos.setBackground(new java.awt.Color(51, 51, 51));
        bttnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/truck.png"))); // NOI18N
        bttnPedidos.setText("Pedidos");
        bttnPedidos.setToolTipText("");
        bttnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(bttnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(bttnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(bttnSugerencias, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(bttnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(bttnCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(bttnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(bttnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        layerPanel.setLayout(new java.awt.CardLayout());
        layerPanel.add(vistaCuenta, "card2");
        layerPanel.add(pantallaUsuarios, "card3");
        layerPanel.add(pantallaSugerencias, "card4");
        layerPanel.add(pantallaProductos, "card5");
        layerPanel.add(pantallaCategorias, "card6");
        layerPanel.add(pantallaPedidos, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layerPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layerPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Cambia el color del botón seleccionado y restablece el de los demás.
     * @param boton Botón que fue seleccionado
     */
    private void seleccionarBoton(JButton boton) {
        bttnInicio.setBackground(Colores.CONTRA_FONDO);
        bttnCategorias.setBackground(Colores.CONTRA_FONDO);
        bttnProductos.setBackground(Colores.CONTRA_FONDO);
        bttnSugerencias.setBackground(Colores.CONTRA_FONDO);
        bttnUsuarios.setBackground(Colores.CONTRA_FONDO);
        bttnCuenta.setBackground(Colores.CONTRA_FONDO);
        bttnPedidos.setBackground(Colores.CONTRA_FONDO);
        boton.setBackground(Colores.PRIMARIO);
    }

    /**
     * Muestra el panel recibido en el área principal de la ventana.
     * @param panel Panel a mostrar (sección seleccionada)
     */
    private void mostrarContenido(JPanel panel) {
        layerPanel.removeAll();
        layerPanel.add(panel);
        layerPanel.revalidate();
        layerPanel.repaint();
    }
    

    /**
     * Acción al presionar el botón "Inicio".
     * Selecciona el botón y muestra un panel vacío (pantalla de inicio).
     */
    private void bttnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnInicioActionPerformed
        seleccionarBoton(bttnInicio);
        mostrarContenido(new JPanel());
    }//GEN-LAST:event_bttnInicioActionPerformed


    /**
     * Acción al presionar el botón "Cuenta".
     * Selecciona el botón y muestra la sección de cuenta del usuario.
     */
    private void bttnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCuentaActionPerformed
        seleccionarBoton(bttnCuenta);
        mostrarContenido(vistaCuenta);
    }//GEN-LAST:event_bttnCuentaActionPerformed


    /**
     * Acción al presionar el botón "Usuarios".
     * Selecciona el botón y muestra la sección de gestión de usuarios.
     */
    private void bttnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUsuariosActionPerformed
        seleccionarBoton(bttnUsuarios);
        mostrarContenido(pantallaUsuarios);
    }//GEN-LAST:event_bttnUsuariosActionPerformed


    /**
     * Acción al presionar el botón "Sugerencias".
     * Selecciona el botón y muestra la sección de gestión de sugerencias.
     */
    private void bttnSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSugerenciasActionPerformed
        seleccionarBoton(bttnSugerencias);
        mostrarContenido(pantallaSugerencias);
    }//GEN-LAST:event_bttnSugerenciasActionPerformed


    /**
     * Acción al presionar el botón "Categorías".
     * Selecciona el botón y muestra la sección de gestión de categorías.
     */
    private void bttnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCategoriasActionPerformed
        seleccionarBoton(bttnCategorias);
        mostrarContenido(pantallaCategorias);
    }//GEN-LAST:event_bttnCategoriasActionPerformed


    /**
     * Acción al presionar el botón "Productos".
     * Selecciona el botón y muestra la sección de gestión de productos.
     */
    private void bttnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnProductosActionPerformed
        seleccionarBoton(bttnProductos);
        mostrarContenido(pantallaProductos);
    }//GEN-LAST:event_bttnProductosActionPerformed


    /**
     * Acción al presionar el botón "Pedidos".
     * Selecciona el botón y muestra la sección de gestión de pedidos.
     */
    private void bttnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPedidosActionPerformed
        seleccionarBoton(bttnPedidos);
        mostrarContenido(pantallaPedidos);
    }//GEN-LAST:event_bttnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     * Método principal. Inicia la aplicación y muestra el menú de administración.
     * Aplica el tema visual FlatMacDarkLaf.
     */
    public static void main(String args[]) {
        try {
            // Establece el tema oscuro tipo macOS
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // Crea y muestra la ventana principal en el hilo de eventos de Swing
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCategorias;
    private javax.swing.JButton bttnCuenta;
    private javax.swing.JButton bttnInicio;
    private javax.swing.JButton bttnPedidos;
    private javax.swing.JButton bttnProductos;
    private javax.swing.JButton bttnSugerencias;
    private javax.swing.JButton bttnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane layerPanel;
    private org.upemor.views.admin.screens.PantallaCategorias pantallaCategorias;
    private org.upemor.views.admin.screens.PantallaPedidos pantallaPedidos;
    private org.upemor.views.admin.screens.PantallaProductos pantallaProductos;
    private org.upemor.views.admin.screens.PantallaSugerencias pantallaSugerencias;
    private org.upemor.views.admin.screens.PantallaUsuarios pantallaUsuarios;
    private org.upemor.views.auth.VistaCuenta vistaCuenta;
    // End of variables declaration//GEN-END:variables
}
