/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.forms;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import org.upemor.controllers.CategoriasControlador;
import org.upemor.models.Categorias;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Validadores;

/**
 * Formulario para agregar nuevas categorías o editar categorías existentes
 * Este panel proporciona una interfaz simple con campos para nombre y descripción
 * Maneja tanto la creación de nuevas categorías como la edición de categorías existentes
 * Incluye validaciones de entrada y comunicación con el controlador de categorías
 * 
 * @author Admin
 */
public class FormularioCategoria extends javax.swing.JPanel {
    // Variables de instancia para la gestión del formulario y controladores
    private CategoriasControlador categoriasCTR;  // Controlador para operaciones CRUD de categorías
    private JDialog dialogo;                     // Diálogo contenedor del formulario
    private Categorias categoria;                // Categoría a editar (null si es nueva categoría)

    /**
     * Constructor único que maneja tanto el modo creación como edición
     * Determina automáticamente el modo basándose en si se proporciona una categoría existente
     * 
     * @param parent Ventana padre que contiene la gestión de categorías
     * @param dialogo Diálogo que contiene este formulario
     * @param categoria Categoría existente a editar (null para crear nueva categoría)
     */
    public FormularioCategoria(JDialog dialogo, Categorias categoria) {
        initComponents();
        this.dialogo = dialogo;
        categoriasCTR = new CategoriasControlador();

        // Si no se proporciona categoría, permanece en modo creación
        if (categoria == null) return;
        
        // Si se proporciona categoría, configura el modo edición
        this.categoria = categoria;
        modoEdicion();
    }

    /**
     * Configura el formulario para modo edición
     * Cambia los textos de la interfaz y carga los datos de la categoría existente
     * Modifica el título y el texto del botón para reflejar que se está editando
     */
    private void modoEdicion() {
        // Cambia los textos de la interfaz para modo edición
        jLabel1.setText("Editar categoria");
        bttnAgregar.setText("Editar");

        // Carga los datos de la categoría existente en los campos
        campoNombre.setText(categoria.getNombre());
        campoDescripcion.setText(categoria.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        campoNombre = new javax.swing.JTextField();
        bttnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bttnAgregar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar categoria");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        campoDescripcion.setColumns(20);
        campoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDescripcion.setLineWrap(true);
        campoDescripcion.setRows(5);
        campoDescripcion.setMaximumSize(new java.awt.Dimension(332, 129));
        campoDescripcion.setMinimumSize(new java.awt.Dimension(332, 129));
        jScrollPane1.setViewportView(campoDescripcion);

        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNombre.setMaximumSize(new java.awt.Dimension(64, 31));

        bttnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        bttnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bttnCancelar.setText("Cancelar");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Descripcion");

        bttnAgregar.setBackground(new java.awt.Color(239, 55, 67));
        bttnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        bttnAgregar.setText("Agregar");
        bttnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(bttnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(bttnAgregar)
                .addGap(54, 54, 54))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador del evento click del botón Agregar/Editar
     * Valida los campos del formulario y realiza la operación correspondiente
     * Determina automáticamente si debe insertar una nueva categoría o actualizar una existente
     * 
     * @param evt Evento del botón
     */
    private void bttnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAgregarActionPerformed
        try {
            // Obtiene los valores de los campos del formulario
            String nombre = campoNombre.getText();
            String descipcion = campoDescripcion.getText();

            // Valida los campos usando la clase Validadores
            Validadores.validarNombre(nombre);
            Validadores.validarTexto(descipcion);

            // Determina si es una actualización o inserción basándose en si existe una categoría
            if (categoria != null) {
                // Modo edición: actualiza la categoría existente
                categoriasCTR.actualizar(categoria.getId(), nombre, descipcion);
            } else {
                // Modo creación: inserta una nueva categoría
                categoriasCTR.insertar(nombre, descipcion);
            }
            
            // Limpia los campos del formulario después de la operación exitosa
            campoNombre.setText("");
            campoDescripcion.setText("");

            // Actualiza la vista padre y cierra el diálogo
            NotificadorGlobal.getInstancia().notificarCambio("actualizacion Categorias", new Object[0]);
            dialogo.setVisible(false);
        } catch (Exception e) {
            // Muestra un mensaje de error si alguna validación falla o hay error en la operación
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnAgregarActionPerformed

    /**
     * Manejador del evento click del botón Cancelar
     * Cierra el diálogo sin guardar cambios ni realizar ninguna operación
     * 
     * @param evt Evento del botón
     */
    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        dialogo.setVisible(false);
    }//GEN-LAST:event_bttnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAgregar;
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}