/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.forms;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import org.upemor.controllers.SugerenciasControlador;
import org.upemor.controllers.UsuariosControlador;
import org.upemor.models.Sugerencias;
import org.upemor.models.Usuarios;
import org.upemor.utils.Validadores;
import org.upemor.views.estudiante.screens.ApartadoSugerencias;

/**
 *
 * @author angelalonso
 */
public class FormularioSugerencia extends javax.swing.JPanel {

    private ApartadoSugerencias padre;
    private JDialog dialogo;
    private SugerenciasControlador sugerenciasCTR;
    private UsuariosControlador usuariosCTR;
    private Sugerencias sugerencia;
    private Usuarios usuario;


    /**
     * Creates new form AgregarSugerencia
     */
    public FormularioSugerencia(ApartadoSugerencias padre, JDialog dialogo, Sugerencias sugerencia) {
        initComponents();
        sugerenciasCTR = new SugerenciasControlador();
        usuariosCTR = new UsuariosControlador();

        this.padre = padre;
        this.dialogo = dialogo;
        this.usuario = usuariosCTR.buscarPorId(padre.getIdUsuario());
        
        if (usuario.getRol().equals("estudiante")) checkRevisado.setVisible(false);
        
        if (sugerencia == null) return;

        this.sugerencia = sugerencia;

        campoAsunto.setText(sugerencia.getAsunto());
        campoComentarios.setText(sugerencia.getComentario());
        jLabel1.setText("Editar sugerencia");
        bttnAceptar.setText("Editar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoComentarios = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        campoAsunto = new javax.swing.JTextField();
        bttnAceptar = new javax.swing.JButton();
        bttnCancelar = new javax.swing.JButton();
        checkRevisado = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nueva sugerencia");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Comentarios");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(334, 131));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(334, 131));

        campoComentarios.setColumns(20);
        campoComentarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoComentarios.setLineWrap(true);
        campoComentarios.setRows(5);
        campoComentarios.setMaximumSize(new java.awt.Dimension(13, 29));
        jScrollPane1.setViewportView(campoComentarios);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Asunto");

        campoAsunto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoAsunto.setMaximumSize(new java.awt.Dimension(64, 31));

        bttnAceptar.setBackground(new java.awt.Color(239, 55, 67));
        bttnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        bttnAceptar.setText("Agregar");
        bttnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAceptarActionPerformed(evt);
            }
        });

        bttnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCancelar.setText("Cancelar");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });

        checkRevisado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkRevisado.setText("Revisado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkRevisado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttnCancelar)
                        .addGap(298, 298, 298)
                        .addComponent(bttnAceptar))
                    .addComponent(campoAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkRevisado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAceptarActionPerformed
        try {
            String asunto = campoAsunto.getText();
            String comentarios = campoComentarios.getText();

            Validadores.validarNombre(asunto);
            Validadores.validarTexto(comentarios);

            if (sugerencia == null) sugerenciasCTR.insertar(usuario.getId(), asunto, comentarios);
            
            else sugerenciasCTR.actualizar(sugerencia, asunto, comentarios, checkRevisado.isSelected() ? "revisada" : "pendiente");
            
            padre.cargarVista();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        dialogo.setVisible(false);
    }//GEN-LAST:event_bttnAceptarActionPerformed

    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        dialogo.setVisible(false);
    }//GEN-LAST:event_bttnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAceptar;
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JTextField campoAsunto;
    private javax.swing.JTextArea campoComentarios;
    private javax.swing.JCheckBox checkRevisado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
