/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.forms;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import org.upemor.controllers.SugerenciasControlador;
import org.upemor.models.Sugerencias;
import org.upemor.models.Usuarios;
import org.upemor.theme.Colores;
import org.upemor.utils.NotificadorGlobal;

/**
 *
 * @author Admin
 */
public class VistaSugerencia extends javax.swing.JPanel {
    private JDialog dialogo;                 // Diálogo que contiene este panel
    private Sugerencias sugerencia;
    private SugerenciasControlador sugerenciasCTR;

    /**
     * Creates new form VistaSugerencia
     */
    public VistaSugerencia(JDialog dialogo, Sugerencias sugerencia) {
        initComponents();

        sugerenciasCTR = new SugerenciasControlador();
        this.dialogo = dialogo;
        this.sugerencia = sugerencia;
        
        textoAsunto.setText(sugerencia.getAsunto());
        Usuarios autor = sugerencia.getUsuario();
        textoAutor.setText(autor.getNombre() + " " + autor.getApellidoPaterno() + " " + autor.getApellidoMaterno());
        textoFecha.setText(sugerencia.getFechaRegistro() + " ");
        textoComentario.setText(sugerencia.getComentario());
        
        boolean isVisto = sugerencia.getEstado().equals("revisada");
        
        textoFechaVista.setText(isVisto? sugerencia.getFechaRevision() + "": "");

        bttnVisto.setEnabled(!isVisto);
        bttnVisto.setBackground(Colores.SECUNDARIO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoAsunto = new javax.swing.JLabel();
        textoAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoComentario = new javax.swing.JTextArea();
        textoFecha = new javax.swing.JLabel();
        bttnVisto = new javax.swing.JButton();
        textoFechaVista = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        textoAsunto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoAsunto.setForeground(new java.awt.Color(255, 255, 255));
        textoAsunto.setText("[Asunto]");

        textoAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoAutor.setText("[Autor]");

        textoComentario.setEditable(false);
        textoComentario.setColumns(20);
        textoComentario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoComentario.setLineWrap(true);
        textoComentario.setRows(5);
        textoComentario.setFocusable(false);
        jScrollPane1.setViewportView(textoComentario);

        textoFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoFecha.setText("[Fecha]");

        bttnVisto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnVisto.setForeground(new java.awt.Color(255, 255, 255));
        bttnVisto.setText("Visto");
        bttnVisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVistoActionPerformed(evt);
            }
        });

        textoFechaVista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoFechaVista.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        textoFechaVista.setText("[FechaVista]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoFechaVista, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addComponent(textoAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnVisto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(textoAsunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoFecha)
                    .addComponent(bttnVisto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFechaVista)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnVistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVistoActionPerformed
        int OK = JOptionPane.showConfirmDialog(
            SwingUtilities.getWindowAncestor(this),
            "Confirmar vista de la sugerencia?",
            "Dar por visto la sugerencia",
            JOptionPane.YES_NO_OPTION
        );

        if (OK == JOptionPane.YES_OPTION) {
            dialogo.setVisible(false);

            boolean res = sugerenciasCTR.marcarSugerenciaLeida(sugerencia.getId());

            if (!res) {
                JOptionPane.showMessageDialog(this, "No se pudo realizar la accion", "Error al marcar como leido", JOptionPane.CLOSED_OPTION);
                return;
            }

            NotificadorGlobal.getInstancia().notificarCambio("actualizar lista Sugerencias", new Object[0]);
        }
            
    }//GEN-LAST:event_bttnVistoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnVisto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textoAsunto;
    private javax.swing.JLabel textoAutor;
    private javax.swing.JTextArea textoComentario;
    private javax.swing.JLabel textoFecha;
    private javax.swing.JLabel textoFechaVista;
    // End of variables declaration//GEN-END:variables
}
