/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.forms;

import java.util.List;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import org.upemor.controllers.PedidosControlador;
import org.upemor.models.ItemDetallePedido;
import org.upemor.models.Productos;
import org.upemor.models.Usuarios;
import org.upemor.utils.NotificadorGlobal;
import org.upemor.utils.Receptor;

/**
 *
 * @author Admin
 */
public class VistaPedidos extends javax.swing.JPanel implements Receptor {
    private PedidosControlador pedidosCTR;
    private List<ItemDetallePedido> listaCarrito;
    private Usuarios usuario;
    private JDialog dialogo;
    /**
     * Creates new form VistaPedidos
     */
    public VistaPedidos(JDialog dialogo, List<ItemDetallePedido> listaCarrito) {
        NotificadorGlobal.getInstancia().registrar(this);
        pedidosCTR = new PedidosControlador();
        initComponents();
        this.dialogo = dialogo;
        this.listaCarrito = listaCarrito;
        
        if (listaCarrito.size() < 1) {
            bttnBorrar.setEnabled(false);
            bttnRealizarPedido.setEnabled(false);
        }
        
        panelListaEntidades.tieneEdicion(false);
        panelListaEntidades.setVistaDetalles();
        panelListaEntidades.actualizarLista(listaCarrito);
        
        calcularTotal();
    }

    private void calcularTotal() {
        double total = 0;
        for (ItemDetallePedido item : listaCarrito) {
            total += item.getTotal();
        }
        textoTotal.setText("$" + total);
    }

    public void setUsuario(Usuarios usuario) {
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelListaEntidades = new org.upemor.widgets.PanelListaEntidades<ItemDetallePedido>();
        bttnCerrar = new javax.swing.JButton();
        bttnRealizarPedido = new javax.swing.JButton();
        bttnBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textoTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMensaje = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Carrito de compras");

        bttnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        bttnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bttnCerrar.setText("Cerrar");
        bttnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarActionPerformed(evt);
            }
        });

        bttnRealizarPedido.setBackground(new java.awt.Color(33, 150, 243));
        bttnRealizarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnRealizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        bttnRealizarPedido.setText("Realizar pedido");
        bttnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRealizarPedidoActionPerformed(evt);
            }
        });

        bttnBorrar.setBackground(new java.awt.Color(239, 55, 67));
        bttnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        bttnBorrar.setText("Borrar lista");
        bttnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBorrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Total a pagar: ");

        textoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoTotal.setText("$[Total]");

        campoMensaje.setColumns(20);
        campoMensaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoMensaje.setLineWrap(true);
        campoMensaje.setRows(5);
        jScrollPane1.setViewportView(campoMensaje);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelListaEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarActionPerformed
        dialogo.setVisible(false);
        NotificadorGlobal.getInstancia().notificarCambio("cerrar Carrito", new Object[] {listaCarrito});
        NotificadorGlobal.getInstancia().remover(this);
    }//GEN-LAST:event_bttnCerrarActionPerformed

    private void bttnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRealizarPedidoActionPerformed
        if (listaCarrito.size() < 1) {
            JOptionPane.showMessageDialog(this, "No hay productos en el carrito");
            return;
        }

        int OK = JOptionPane.showConfirmDialog(this, "Seguro que quieres pedir ya?", "Realizar pedido", JOptionPane.YES_NO_OPTION);

        if (OK == JOptionPane.NO_OPTION) return;

        try {
            String comentario = campoMensaje.getText();

            if (comentario.isEmpty()) comentario = "Sin comentarios";

            if (usuario == null) {
                JOptionPane.showMessageDialog(this, "Debes iniciar sesión para realizar un pedido");
                return;
            }

            pedidosCTR.crearPedido(usuario, listaCarrito, comentario);
            
            listaCarrito.clear();
            panelListaEntidades.actualizarLista(listaCarrito);
            textoTotal.setText("$0.0");
            campoMensaje.setText("");
            
            NotificadorGlobal.getInstancia().notificarCambio("actualizacion de Pedido", new Object[] {});

            JOptionPane.showMessageDialog(this, "Pedido realizado con éxito");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al realizar el pedido: " + e.getMessage());
            System.err.println(e);
            e.printStackTrace();
        }
        
        dialogo.setVisible(false);
        NotificadorGlobal.getInstancia().remover(this);
    }//GEN-LAST:event_bttnRealizarPedidoActionPerformed

    private void bttnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBorrarActionPerformed
        int OK = JOptionPane.showConfirmDialog(this, "Seguro que quieres borrar el carrito?", "Borrar carrito", JOptionPane.YES_NO_OPTION);

        if (OK == JOptionPane.YES_OPTION) {
            listaCarrito.clear();
            panelListaEntidades.actualizarLista(listaCarrito);
            bttnBorrar.setEnabled(false);
            bttnRealizarPedido.setEnabled(false);
            textoTotal.setText("$0.0");
            campoMensaje.setText("");
            
            NotificadorGlobal.getInstancia().notificarCambio("borrar Pedido", new Object[] {});
        }
    }//GEN-LAST:event_bttnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnBorrar;
    private javax.swing.JButton bttnCerrar;
    private javax.swing.JButton bttnRealizarPedido;
    private javax.swing.JTextArea campoMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.upemor.widgets.PanelListaEntidades<ItemDetallePedido> panelListaEntidades;
    private javax.swing.JLabel textoTotal;
    // End of variables declaration//GEN-END:variables
    @Override
    public void onReceptor(String msg, Object[] objetos) {
        if (msg.equals("agregar Carrito")) {
            panelListaEntidades.actualizarLista(listaCarrito);
        }

        if (msg.equals("detalle ItemDetallePedido")) {
            ItemDetallePedido itm = (ItemDetallePedido) objetos[0];
            Productos producto = itm.getProducto();
            JDialog dialog = new JDialog(SwingUtilities.getWindowAncestor(this), "Ver producto", JDialog.ModalityType.APPLICATION_MODAL);
            
            int cantidad = itm.getCantidad();
            System.out.println("Detalle Pedido");
            VistaProducto vistaProducto = new VistaProducto(dialog, producto, cantidad, itm.getObservacion());

            dialog.setSize(800, 800);
            dialog.add(vistaProducto);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }

        if (msg.equals("eliminar ItemDetallePedido") || msg.equals("eliminacion ItemDetallePedido")) {
            ItemDetallePedido itm = (ItemDetallePedido) objetos[0];
            
            for (int i = 0; i < listaCarrito.size(); i++) {
                ItemDetallePedido item = listaCarrito.get(i);
                
                if (item.getProducto().getId() == itm.getProducto().getId()) {
                    listaCarrito.remove(i);
                    break;
                }
            }
            if (listaCarrito.size() < 1) {
                bttnBorrar.setEnabled(false);
                bttnRealizarPedido.setEnabled(false);
            }
            panelListaEntidades.actualizarLista(listaCarrito);
            calcularTotal();
        }
    }
}
