/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.forms;

import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

import org.upemor.models.ItemDetallePedido;
import org.upemor.models.Productos;
import org.upemor.utils.NotificadorGlobal;

/**
 * Panel que muestra la vista detallada de un producto.
 * Permite visualizar la información, imagen, editar o eliminar el producto.
 * 
 * @author angelalonso
 */
public class VistaProducto extends javax.swing.JPanel {
    // Diálogo donde se muestra este panel
    private JDialog dialogo;
    private Productos producto;
    private int actualCantidad = -1;
    private int cantidad = -1;
    private double total = 0;

    /**
     * Constructor que inicializa la vista con un producto específico.
     * @param parent Panel padre que contiene esta vista.
     * @param dialogo Diálogo contenedor.
     * @param producto Producto a mostrar.
     */
    public VistaProducto(JDialog dialogo, Productos producto) {
        initComponents();
        this.dialogo = dialogo;
        this.producto = producto;
        panelAgregarCarrito.setVisible(false);
        textoObservaciones.setVisible(false);
        campoObservaciones.setVisible(false);


        mostrarInfo();
        
    }

    public VistaProducto(JDialog dialogo, Productos producto, int cantidad, String observacion) {
        initComponents();
        this.dialogo = dialogo;
        this.producto = producto;
        this.actualCantidad = cantidad;
        this.cantidad = cantidad;

        campoObservaciones.setVisible(true);
        campoObservaciones.setText(observacion);
        campoObservaciones.setEditable(cantidad > 0);
        
        if (cantidad > 50) bttnMas.setEnabled(false);
        
        if (cantidad < 1) bttnMenos.setEnabled(false);
        
        calcularMostrarCantidad();

        mostrarInfo();
    }
    
    private void calcularMostrarCantidad() {
        textoCantidad.setText(cantidad + "");
        total = cantidad * producto.getPrecio();
        textoTotal.setText(total + "");
    }

    private void mostrarInfo() {
        // Mostrar estado de disponibilidad
        String estado = producto.isDisponible() ? "Disponible" : "No Disponible";
        
        // Llenar etiquetas con los datos del producto
        textoId.setText(producto.getId() + "");
        textoNombre.setText(producto.getNombreProducto());
        campoDescripcion.setText(producto.getDescripcion());
        textoDisponible.setText(estado);
        textoPrecio.setText("Precio: $" + producto.getPrecio());
        tetxoFecha.setText(producto.getFechaRegistro() + "");
        textoPreparacion.setText("Tiempo de preparación: " + producto.getTiempoPreparacion());
        textoCategorias.setText(String.format("<html><body>Categorías: %s</body></html>", producto.getNombresCategorias()));

        // Cargar la imagen desde la ruta en un hilo separado para no bloquear la interfaz
        SwingUtilities.invokeLater(() -> {
            cargarImagenDesdeRuta(producto.getImagen());
        });
    }

    /**
     * Carga y escala la imagen del producto desde una ruta relativa para mostrarla en la etiqueta correspondiente.
     * @param rutaImagen Ruta relativa de la imagen (puede ser null)
     */
    private void cargarImagenDesdeRuta(String rutaImagen) {
        if (rutaImagen == null || rutaImagen.isEmpty()) {
            textoImagen.setIcon(null);
            textoImagen.setText("Sin imagen");
            return;
        }
        try {
            java.io.File imgFile = new java.io.File("img/" + rutaImagen);
            if (!imgFile.exists()) {
                textoImagen.setIcon(null);
                textoImagen.setText("Sin imagen");
                return;
            }
            ImageIcon icono = new ImageIcon(imgFile.getAbsolutePath());
            int ancho = textoImagen.getWidth() > 0 ? textoImagen.getWidth() : 366;
            int alto = textoImagen.getHeight() > 0 ? textoImagen.getHeight() : 380;
            Image imagenEscalada = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            textoImagen.setIcon(new ImageIcon(imagenEscalada));
            textoImagen.setText("");
        } catch (Exception e) {
            textoImagen.setText("Error al cargar imagen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoNombre = new javax.swing.JLabel();
        textoImagen = new javax.swing.JLabel();
        textoPrecio = new javax.swing.JLabel();
        textoPreparacion = new javax.swing.JLabel();
        textoDisponible = new javax.swing.JLabel();
        bttnCerrar = new javax.swing.JButton();
        textoCategorias = new javax.swing.JLabel();
        tetxoFecha = new javax.swing.JLabel();
        fechaJlabel = new javax.swing.JLabel();
        textoId = new javax.swing.JLabel();
        panelAgregarCarrito = new javax.swing.JPanel();
        bttnMas = new javax.swing.JButton();
        bttnMenos = new javax.swing.JButton();
        textoCantidad = new javax.swing.JLabel();
        textoTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservaciones = new javax.swing.JTextArea();
        textoObservaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));

        textoNombre.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        textoNombre.setText("[Nombre]");

        textoImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        textoImagen.setMaximumSize(new java.awt.Dimension(368, 390));
        textoImagen.setMinimumSize(new java.awt.Dimension(368, 390));
        textoImagen.setPreferredSize(new java.awt.Dimension(368, 390));

        textoPrecio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoPrecio.setText("[Precio]");

        textoPreparacion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoPreparacion.setText("[Preparacion]");

        textoDisponible.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        textoDisponible.setText("[Disponible]");

        bttnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        bttnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCerrar.setText("Cerrar");
        bttnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarActionPerformed(evt);
            }
        });

        textoCategorias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCategorias.setText("[Categorias]");
        textoCategorias.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tetxoFecha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tetxoFecha.setText("[Fecha]");

        fechaJlabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fechaJlabel.setText("Fecha de creacion:");

        textoId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoId.setText("[id]");

        bttnMas.setBackground(new java.awt.Color(239, 55, 67));
        bttnMas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnMas.setForeground(new java.awt.Color(255, 255, 255));
        bttnMas.setText("+");
        bttnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMasActionPerformed(evt);
            }
        });

        bttnMenos.setBackground(new java.awt.Color(33, 150, 243));
        bttnMenos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnMenos.setForeground(new java.awt.Color(255, 255, 255));
        bttnMenos.setText("-");
        bttnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMenosActionPerformed(evt);
            }
        });

        textoCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCantidad.setText("0");

        textoTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoTotal.setText("[Precio total]");

        javax.swing.GroupLayout panelAgregarCarritoLayout = new javax.swing.GroupLayout(panelAgregarCarrito);
        panelAgregarCarrito.setLayout(panelAgregarCarritoLayout);
        panelAgregarCarritoLayout.setHorizontalGroup(
            panelAgregarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarCarritoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAgregarCarritoLayout.setVerticalGroup(
            panelAgregarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarCarritoLayout.createSequentialGroup()
                .addGroup(panelAgregarCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        campoObservaciones.setColumns(20);
        campoObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoObservaciones.setLineWrap(true);
        campoObservaciones.setRows(5);
        jScrollPane1.setViewportView(campoObservaciones);

        textoObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoObservaciones.setText("Observaciones");

        campoDescripcion.setEditable(false);
        campoDescripcion.setColumns(20);
        campoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDescripcion.setLineWrap(true);
        campoDescripcion.setRows(5);
        campoDescripcion.setBorder(null);
        jScrollPane2.setViewportView(campoDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAgregarCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoCategorias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoPreparacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDisponible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tetxoFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaJlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoObservaciones, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPreparacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaJlabel)
                        .addGap(10, 10, 10)
                        .addComponent(tetxoFecha)
                        .addGap(18, 18, 18)
                        .addComponent(textoObservaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Evento botón cerrar: Oculta el diálogo que contiene esta vista
    private void bttnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarActionPerformed
        dialogo.setVisible(false);
        if (cantidad > 0 || actualCantidad != cantidad) {
            NotificadorGlobal.getInstancia().notificarCambio("agregar Carrito", new Object[] {new ItemDetallePedido(producto, cantidad, total, campoObservaciones.getText())});
        }
    }//GEN-LAST:event_bttnCerrarActionPerformed

    private void bttnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMasActionPerformed
        cantidad++;

        if (cantidad >= 50) {
            bttnMas.setEnabled(false);
            campoObservaciones.setEditable(false);
            calcularMostrarCantidad();
            return;
        }
        

        if (cantidad > 0) {
            bttnMenos.setEnabled(true);
            campoObservaciones.setEditable(true);
        }

        calcularMostrarCantidad();
    }//GEN-LAST:event_bttnMasActionPerformed

    private void bttnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMenosActionPerformed
        cantidad--;

        if (cantidad < 1) {
            bttnMenos.setEnabled(false);
            campoObservaciones.setEditable(false);
            calcularMostrarCantidad();
            return;
        }
        

        if (cantidad > 0) {
            bttnMas.setEnabled(true);
            campoObservaciones.setEditable(true);
        }

        calcularMostrarCantidad();
    }//GEN-LAST:event_bttnMenosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCerrar;
    private javax.swing.JButton bttnMas;
    private javax.swing.JButton bttnMenos;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextArea campoObservaciones;
    private javax.swing.JLabel fechaJlabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelAgregarCarrito;
    private javax.swing.JLabel tetxoFecha;
    private javax.swing.JLabel textoCantidad;
    private javax.swing.JLabel textoCategorias;
    private javax.swing.JLabel textoDisponible;
    private javax.swing.JLabel textoId;
    private javax.swing.JLabel textoImagen;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoObservaciones;
    private javax.swing.JLabel textoPrecio;
    private javax.swing.JLabel textoPreparacion;
    private javax.swing.JLabel textoTotal;
    // End of variables declaration//GEN-END:variables
}
