/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.upemor.views.forms;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import org.upemor.controllers.PedidosControlador;
import org.upemor.models.DetallePedido;
import org.upemor.models.Pedidos;
import org.upemor.theme.Colores;
import org.upemor.utils.NotificadorGlobal;

/**
 *
 * @author Admin
 */
public class VistaDetallePedido extends javax.swing.JPanel {
    private PedidosControlador pedidosCTR;
    private JDialog dialog;
    private Pedidos pedido;
    private String rolUsuario;

    /**
     * Creates new form VistaDetallePedido
     */
    public VistaDetallePedido(JDialog dialog, Pedidos pedido, String rolUsuario) {
        pedidosCTR = new PedidosControlador();
        initComponents();
        
        this.dialog = dialog;
        this.pedido = pedido;
        this.rolUsuario = rolUsuario;
        
        configurarPanelLista();
        cargarDatosPedido();
        configurarEstadoYPantalla();
    }

    private void configurarPanelLista() {
        panelListaEntidades1.tieneEdicion(false);
        panelListaEntidades1.tieneEliminacion(false);
        panelListaEntidades1.actualizarLista(
            pedidosCTR.obtenerDetallesPorIdPedido(pedido.getId())
        );
    }

    private void cargarDatosPedido() {
        textoFolio.setText(pedido.getFolio());
        textoUsuario.setText(pedido.getUsuario().getNombre() + " " + pedido.getUsuario().getApellidoPaterno() + " " + pedido.getUsuario().getApellidoMaterno());
        campoMensaje.setText(pedido.getComentario());
        textoDetalles.setText(
            "Tiempo estimado: " + pedido.getTiempoEstimado() + ", " + pedido.getFechaPedido()
        );
    }

    private void configurarEstadoYPantalla() {
        String estado = pedido.getEstado();

        textoEstado.setText(capitalizar(estado));

        // Configuración de botones según rol y estado
        if ("estudiante".equals(rolUsuario)) {
            configurarBotonParaEstudiante(estado);
        } else {
            configurarBotonParaEmpleado(estado);
        }
    }

    private void configurarBotonParaEstudiante(String estado) {
        if ("pendiente".equals(estado)) {
            bttnCambiarEstado.setText("Cancelar");
            bttnCambiarEstado.setBackground(Colores.PRIMARIO);
        } else {
            bttnCambiarEstado.setEnabled(false);
        }
    }

    private void configurarBotonParaEmpleado(String estado) {
        switch (estado) {
            case "cancelado":
                bttnCambiarEstado.setEnabled(false);
                break;
            case "pendiente":
                bttnCambiarEstado.setText("Preparar");
                bttnCambiarEstado.setBackground(Colores.SECUNDARIO);
                break;
            case "preparando":
                bttnCambiarEstado.setText("Listo");
                bttnCambiarEstado.setBackground(Colores.ON_SECUNDARIO);
                break;
            case "listo":
                bttnCambiarEstado.setText("Listo");
                bttnCambiarEstado.setEnabled(false);
                break;
            default:
                break;
        }
    }

    private String capitalizar(String texto) {
        return texto.substring(0, 1).toUpperCase() + texto.substring(1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoFolio = new javax.swing.JLabel();
        panelListaEntidades1 = new org.upemor.widgets.PanelListaEntidades<DetallePedido>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMensaje = new javax.swing.JTextArea();
        textoUsuario = new javax.swing.JLabel();
        textoEstado = new javax.swing.JLabel();
        bttnCambiarEstado = new javax.swing.JButton();
        bttnCerrar = new javax.swing.JButton();
        textoDetalles = new javax.swing.JLabel();

        textoFolio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoFolio.setText("[Folio]");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mensaje");

        campoMensaje.setEditable(false);
        campoMensaje.setColumns(20);
        campoMensaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoMensaje.setLineWrap(true);
        campoMensaje.setRows(5);
        campoMensaje.setBorder(null);
        jScrollPane1.setViewportView(campoMensaje);

        textoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoUsuario.setText("[Solicitador]");

        textoEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoEstado.setText("[Estado]");

        bttnCambiarEstado.setBackground(new java.awt.Color(51, 51, 51));
        bttnCambiarEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCambiarEstado.setText("Cancelar");
        bttnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCambiarEstadoActionPerformed(evt);
            }
        });

        bttnCerrar.setBackground(new java.awt.Color(51, 51, 51));
        bttnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bttnCerrar.setText("Cerrar");
        bttnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarActionPerformed(evt);
            }
        });

        textoDetalles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoDetalles.setText("[Tiempo preparacion, Fecha registro]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnCerrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoDetalles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                            .addComponent(bttnCambiarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelListaEntidades1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoFolio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(textoFolio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListaEntidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCambiarEstadoActionPerformed
        if (rolUsuario == "") return;

        int OK = JOptionPane.showConfirmDialog(this, "¿Estás seguro de cambiar el estado del pedido?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (OK == JOptionPane.NO_OPTION) {
            bttnCambiarEstado.setEnabled(true);
            return;
        }

        bttnCambiarEstado.setEnabled(false);

        try {
            String nuevoEstado = "";
            switch (bttnCambiarEstado.getText()) {
                case "Cancelar":
                    nuevoEstado = "cancelado";
                    break;
                case "Preparar":
                    nuevoEstado = "preparando";
                    break;
                case "Listo":
                    nuevoEstado = "listo";
                    break;
                default:
                    nuevoEstado = "Error";
                    break;
            }
            
            if (nuevoEstado.equals("Error")) {
                JOptionPane.showMessageDialog(this, "No se puede cambiar el estado del pedido");
                return;
            }

            pedidosCTR.actualizarEstado(pedido.getId(), nuevoEstado);
            NotificadorGlobal.getInstancia().notificarCambio("actualizacion de Pedido",new Object[0]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cambiar estado: " + e.getMessage());
        }
    }//GEN-LAST:event_bttnCambiarEstadoActionPerformed

    private void bttnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarActionPerformed
        dialog.setVisible(false);
    }//GEN-LAST:event_bttnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCambiarEstado;
    private javax.swing.JButton bttnCerrar;
    private javax.swing.JTextArea campoMensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.upemor.widgets.PanelListaEntidades<DetallePedido> panelListaEntidades1;
    private javax.swing.JLabel textoDetalles;
    private javax.swing.JLabel textoEstado;
    private javax.swing.JLabel textoFolio;
    private javax.swing.JLabel textoUsuario;
    // End of variables declaration//GEN-END:variables
}
